from pathlib import Path
from devmemory import Memory

def test_search_end_to_end(tmp_path: Path):
    db_path = tmp_path / "test_store.db"
    memory = Memory(db_path=db_path)
    
    # 1. Capture a memory (this saves to SQLite, passes through AI, and saves to Vector Store)
    memory.capture(source="manual", raw_text="I fixed a bug in the database")
    
    # 2. Search for it!
    results = memory.search("Find me database bugs")
    
    # 3. Prove that our search successfully pulled the MemoryRecord all the way out!
    assert len(results) == 1
    assert results[0].type.value == "note"
    assert results[0].summary == "Fake summary generated by dummy AI"
