from typing import Protocol

class LLMClient(Protocol):
    """An interface for talking to an LLM."""
    
    def extract_memory_record(self, raw_text: str, source: str, metadata: dict) -> dict:
        """Takes raw text and asks the LLM to extract the structured data (type, summary, reasoning, etc) as a dictionary."""
         
class DummyLLMClient:
    """A fake AI that just returns hardcoded data so we can test our pipeline."""
    
    def extract_memory_record(self, raw_text: str, source: str, metadata: dict) -> dict:
        # Notice how this perfectly matches the rule we set in the Protocol above!
        return {
            "type": "note",
            "summary": "Fake summary generated by dummy AI",
            "reasoning": "Fake reasoning because we didn't call a real API.",
            "tags": ["dummy", "test"],
            "related_files": []
        }
